---
# Title: role-mariadb-server-10.5
#
# Author: Bitfinity-NL / L. Rutten
# File: tasks/logical-db-backup.yml
#
# Description:
#   Playbook for creating MariaDB Backups.yml
#
# Sources:
#   https://www.robpeck.com/2018/06/backing-up-and-rotating-mysql-databases-the-easy-way/


/opt/tools/mariadb/scripts

- name: "Create MariaDB directory structure"
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0600
    
- name: "Transfer template(s)"
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.wheel }}"
  with_items:
    - { src: '.my.cnf.j2', dest: '~/root/.my.cnf', owner: 'root', mode: 'root', mode: '0600' }
    - { src: 'logical-db-backup.sh.j2', dest: '{{ mariadb-backup-path }}/logical-db-backup.sh', owner: 'backup', mode: 'backup', mode: '0640' }
    - { src: 'schedule-logical-db-backup.sh.j2', dest: '/etc/logrotate.d/schedule-logical-db-backup.sh', owner: 'root', mode: 'root', mode: '0644' }
