---
# Title: role-mariadb-server-10.5
#
# Author: bitfinity-nl
# File: tasks/main.yml
#
# Description:
#  MariaDB Server is the leading open source database.

- name: "Install on Ubuntu 20.04lts AMD64"
  import_tasks: ubt-2004-amd64.yml
  when:
    - ansible_distribution_version == "20.04"
    - ansible_architecture == "x86_64"
    
- name: "Configure (logical) MariaDB backup"
  import_tasks: mariadb-backup-logical.yml
  when:
    - mariadb_backup_type == 'logical'
    - ansible_distribution_version == "20.04"
    - ansible_architecture == "x86_64"    

- name: "Remove MariaDB backup"
  import_tasks: mariadb-backup-logical.yml
  when:
    - mariadb_backup_type == 'none'
    - ansible_distribution_version == "20.04"
    - ansible_architecture == "x86_64"   
