---
# Title: role-mariadb-server-10.5
#
# Author: Bitfinity-NL / L. Rutten
# File: tasks/logical-db-backup.yml
#
# Description:
#   Playbook for creating MariaDB Backups.yml
#
# Sources:
#   https://www.robpeck.com/2018/06/backing-up-and-rotating-mysql-databases-the-easy-way/

- name: "Create MariaDB directory structure"
  ansible.builtin.file:
    path: "{{ mariadb_backup_path }}"
    state: directory
    owner: root
    group: root
    mode: 0600
    
- name: "Transfer template(s)"
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - { src: '.my.cnf.j2', dest: '/root/.my.cnf', owner: 'root', group: 'root', mode: '0600' }
    - { src: 'mariadb-backup-logical.sh.j2', dest: '/root/mariadb-backup.sh', owner: 'backup', group: 'backup', mode: '0600' }

- name: "Schedule backup script"
  cron:
    name: "Schedule database backup daily at 05 minutes past 0:00"
    minute: "{{ mariadb_backup_minute }}"
    hour: "{{ mariadb_backup_hour }}"
    job: "cd /root/ ; /root/mariadb-backup.sh >/dev/null 2>&1"
